const data = {
  products: [
    {
      id: 1,
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A polpular shirt',
    },
    {
      id: 2,
      name: 'Fit Shirt2',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A polpular shirt',
    },
    {
      id: 3,
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A polpular shirt',
    },
    {
      id: 4,
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Olver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A polpular shirt',
    },
    {
      id: 5,
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A polpular shirt',
    },
    {
      id: 6,
      name: 'Classic Pants',
      slug: 'clssic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A polpular shirt',
    },
  ],
};

export default data;
